# --- Grid States ---
EMPTY = 0
RED_SOLDIER = 2
BLUE_SOLDIER = 3
RED_BASE_ARMOR = 4
RED_BASE_CORE = 5
BLUE_BASE_ARMOR = 6
BLUE_BASE_CORE = 7

# --- Rendering Colors (RGBA) ---
COLOR_MAP = {
    EMPTY: (10, 10, 15, 255),
    RED_SOLDIER: (255, 50, 50, 255),
    BLUE_SOLDIER: (50, 100, 255, 255),
    RED_BASE_ARMOR: (180, 20, 20, 255),
    RED_BASE_CORE: (255, 150, 150, 255),
    BLUE_BASE_ARMOR: (20, 50, 180, 255),
    BLUE_BASE_CORE: (150, 180, 255, 255),
}

PHEROMONE_SENSE_THRESHOLD = 0.1
EDITOR_GRID_SNAP_SIZE = 10 # Pixels for coarse dragging

# --- VIDEO & RENDERING DIMENSIONS (FOR FINAL 9:16 VIDEO) ---
VIDEO_WIDTH = 1080
VIDEO_HEIGHT = 1920
PIXEL_SCALE = 2
# These margins are for the final video render, not the dashboard UI
VIDEO_TOP_MARGIN = int(VIDEO_HEIGHT * 0.10)
VIDEO_BOTTOM_MARGIN = int(VIDEO_HEIGHT * 0.15)
VIDEO_GAME_AREA_HEIGHT = VIDEO_HEIGHT - VIDEO_TOP_MARGIN - VIDEO_BOTTOM_MARGIN
VIDEO_GAME_AREA_WIDTH = VIDEO_WIDTH

# --- SIMULATION GRID DIMENSIONS (DERIVED FROM VIDEO FORMAT) ---
SIM_HEIGHT = VIDEO_GAME_AREA_HEIGHT // PIXEL_SCALE
SIM_WIDTH = VIDEO_GAME_AREA_WIDTH // PIXEL_SCALE

# --- DASHBOARD UI LAYOUT (FOR THE 16:9 WIDE VIEW) ---
DASHBOARD_WIDTH = 1920
DASHBOARD_HEIGHT = 1080
DASHBOARD_RIGHT_PANEL_WIDTH = 420
# NEW: Define the height for the bottom control panel
DASHBOARD_BOTTOM_PANEL_HEIGHT = 80